import { t, localHref, type Locale } from '@/lib/i18n';
import { SectionHeading, TextLink } from './ui';
import { Icon } from './icons';
import { DocumentFlow } from './document-flow';
import { ArchitectureDiagram } from './architecture-diagram';
import { NetworkDiagram } from './network-diagram';
import { Roadmap } from './roadmap';
export function IdeaSection({ locale = "pl" }: {
    locale?: Locale;
} = {}) { return <section id="idea" className="section container"><div className="idea-layout"><SectionHeading number="01" label={t("IDEA HOMEOS", locale)} title={t("Dane s\u0105 wsz\u0119dzie. Kontekst \u2014 nigdzie.", locale)} locale={locale}>{t("Problemem nie jest brak miejsca na dane. Problemem jest brak kontekstu.", locale)}</SectionHeading><div className="idea-explanation"><p>{t("Polisa w mailu. Instrukcja w folderze. Faktura na Google Drive. Termin przegl\u0105du \u2014 gdzie\u015B w pami\u0119ci.", locale)}</p><p>{t("HomeOS ma \u0142\u0105czy\u0107 te informacje z konkretn\u0105 osob\u0105, pojazdem lub urz\u0105dzeniem. Cyfrowy segregator dokument\u00F3w staje si\u0119 cz\u0119\u015Bci\u0105 modelu ca\u0142ego domu.", locale)}</p></div></div><div className="scattered-sources"><span>{t("Segregatory", locale)}</span><span>{t("Foldery i PDF-y", locale)}</span><span>{t("iCloud", locale)}</span><span>{t("Google Drive", locale)}</span><span>{t("Maile", locale)}</span><span>{t("Aplikacje producent\u00F3w", locale)}</span><span>{t("Home Assistant", locale)}</span><span>{t("Monitoring", locale)}</span></div><div className="idea-result"><Icon name="box" size={19}/><span>{t("Jeden obiekt \u0142\u0105czy informacje z wielu miejsc.", locale)}</span><span className="mono">{t("plik \u2192 relacja \u2192 kontekst", locale)}</span></div></section>; }
export function DocumentsSection({ locale = "pl" }: {
    locale?: Locale;
} = {}) { return <section className="section container"><div className="section-top"><SectionHeading number="03" label={t("DOKUMENTY", locale)} title={t("Od pliku do informacji.", locale)} locale={locale}>{t("Paperless-ngx odczytuje dokument. Core wi\u0105\u017Ce go z Twoim domem. Wyszukiwanie pozwala wr\u00F3ci\u0107 do informacji wtedy, gdy jest potrzebna.", locale)}</SectionHeading><TextLink href={localHref("/documents/", locale)} locale={locale}>{t("Przep\u0142yw dokument\u00F3w", locale)}</TextLink></div><DocumentFlow locale={locale}/><div className="tech-footline"><span>{t("ZAKRES MVP", locale)}</span><span>{t("Core", locale)}</span><span>{t("Paperless-ngx", locale)}</span><span>{t("OCR", locale)}</span><span>{t("PostgreSQL", locale)}</span><span>{t("Wyszukiwanie", locale)}</span><span>{t("Relacje dokument\u2013obiekt", locale)}</span></div></section>; }
export function ArchitectureSection({ locale = "pl" }: {
    locale?: Locale;
} = {}) { return <section className="dark-section"><div className="container section"><div className="section-top"><SectionHeading number="04" label={t("ARCHITEKTURA", locale)} title={t("Czytelne granice. Wsp\u00F3lny system.", locale)} locale={locale}>{t("Core odpowiada za kontekst. Wyspecjalizowane us\u0142ugi zajmuj\u0105 si\u0119 dokumentami, kolejk\u0105 zada\u0144 i przechowywaniem danych.", locale)}</SectionHeading><TextLink href={localHref("/architecture/", locale)} locale={locale}>{t("Poznaj zale\u017Cno\u015Bci", locale)}</TextLink></div><ArchitectureDiagram locale={locale}/></div></section>; }
export function NetworkSection({ locale = "pl" }: {
    locale?: Locale;
} = {}) { return <section className="section container"><div className="section-top"><SectionHeading number="05" label={t("INFRASTRUKTURA", locale)} title={t("Dom zaczyna si\u0119 od dobrej sieci.", locale)} locale={locale}>{t("MikroTik CRS310-8G+2S+IN jest g\u0142\u00F3wnym punktem dystrybucji. Okablowanie \u0142\u0105czy pomieszczenia, a dedykowany link SFP+ prowadzi do serwera HomeOS.", locale)}</SectionHeading><TextLink href={localHref("/network/", locale)} locale={locale}>{t("Dokumentacja sieci", locale)}</TextLink></div><NetworkDiagram locale={locale}/><div className="network-summary"><div><h3>{t("Fizyczne po\u0142\u0105czenia", locale)}</h3><p>{t("Osobny plan port\u00F3w, pomieszcze\u0144 i szybkiego linku serwera.", locale)}</p></div><div><h3>{t("Logiczna segmentacja", locale)}</h3><p>{t("Trusted \u00B7 Servers \u00B7 IoT \u00B7 Cameras \u00B7 Guest \u00B7 Lab \u00B7 Management", locale)}</p><TextLink href={localHref("/network/#segmentation", locale)} locale={locale}>{t("Zobacz koncepcj\u0119 segment\u00F3w", locale)}</TextLink></div></div></section>; }
export function LocalFirst({ locale = "pl" }: {
    locale?: Locale;
} = {}) { return <section className="local-section"><div className="container local-layout"><div><div className="eyebrow">{t("06 / LOCAL-FIRST", locale)}</div><h2>{t("Centrum Twojego domu.", locale)}<br />{t("W Twoim domu.", locale)}</h2><p>{t("Dane zostaj\u0105 na w\u0142asnym serwerze. Internet jest opcjonaln\u0105 warstw\u0105 dost\u0119pu i integracji \u2014 nie centralnym miejscem przechowywania.", locale)}</p><div className="local-values"><span><Icon name="shield" size={15}/>{t(" Prywatno\u015B\u0107 i w\u0142asno\u015B\u0107 danych", locale)}</span><span><Icon name="network" size={15}/>{t(" Praca w LAN", locale)}</span><span><Icon name="server" size={15}/>{t(" Self-hosting", locale)}</span></div></div><figure className="local-diagram"><div>{t("Dane domu", locale)}</div><span aria-hidden="true">{t("\u2193", locale)}</span><div className="local-server"><Icon name="server" size={21}/>{t(" HomeOS Server", locale)}</div><span aria-hidden="true">{t("\u2193", locale)}</span><div>{t("Lokalne przechowywanie", locale)}</div><figcaption>{t("Kontrolowany zdalny dost\u0119p i integracje: opcjonalna warstwa poza LAN.", locale)}</figcaption></figure></div></section>; }
export function RoadmapSection({ locale = "pl" }: {
    locale?: Locale;
} = {}) { return <section className="section container"><div className="section-top"><SectionHeading number="07" label={t("KIERUNEK ROZWOJU", locale)} title={t("Najpierw fundament. Potem kolejne warstwy.", locale)} locale={locale}>{t("Obecny MVP skupia si\u0119 na dokumentach, obiektach, wyszukiwaniu i przypomnieniach. Pozosta\u0142e modu\u0142y s\u0105 planowane.", locale)}</SectionHeading><TextLink href={localHref("/roadmap/", locale)} locale={locale}>{t("Pe\u0142na roadmapa", locale)}</TextLink></div><Roadmap locale={locale}/></section>; }
